ecommerce_catalog_product:
    resource: "@EcommerceCatalogBundle/Controller/ProductController.php"
    type:     annotation

ecommerce_catalog_category:
    resource: "@EcommerceCatalogBundle/Controller/CategoryController.php"
    type:     annotation

ecommerce_catalog:
    resource: "@EcommerceCatalogBundle/Resources/config/routing.yml"
    prefix:   /catalog/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# FOS user bundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Lipp_Imagine bundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"