<?php

namespace Ecommerce\CatalogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $title
     * @return string
     * Generate slug form name or title
     */
    public function createUrlKey($title){
        return implode('-',explode(' ',$title));
    }
}
